spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml